### ISSUE TITLE
Problems with the update version

### ISSUE THREAD

**Issue by mohsen-farahani** [jaredpalmer/after.js#312]
## Bug
I updated to version 2.0.0-1 and had this problem

`ERROR: all async routes must have a chunkName property with value of /* webpackChunkName: "MyChunkName" */ check your routes config or use babel-plugin-after`

I use routes this way:
`
 {
        path: '/',
        exact: true,
        component: asyncComponent({
            loader: () => import('./Pages/Home'), // required
            Placeholder: () => <div className="loading progress"></div>, // this is optional, just returns null by default
        }),
    }
`

- After.js Version: 2.0.0-1
- Razzle Version: 3.0.0
- React Version: 16.12.0
- OS: ubuntu 18.04
- Node Version: v12.14.0
- Package Manager and Version:  yarn 1.22.4

**Comment by nimaa77** [comment]
hello, @mohsen-farahani just downgrade to version 1.6.1

`@jaredpalmer/after@1.6.1`

**Comment by nimaa77** [comment]
actually, if you want to test version 2, you must clone `razzle` project from its repository
and `git checkout next` and link razzle to your after.js app

**Comment by nimaa77** [comment]
https://github.com/jaredpalmer/after.js/releases/tag/v3.0.0

the issue should be fixed now :)
@mohsen-farahani please confirm and then close this issue

**Comment by mohsen-farahani** [comment]
@nimaa77

**Comment by mohsen-farahani** [comment]
> https://github.com/jaredpalmer/after.js/releases/tag/v3.0.0
> 
> the issue should be fixed now :)
> @mohsen-farahani please confirm and then close this issue

The problem was not solved

error:
 ERROR  all async routes must have a chunkName property with value of /* webpackChunkName: "MyChunkName" */ check your routes config or use babel-plugin-after

**Comment by nimaa77** [comment]
you should add a property called `chunkName` to your routes array or for simplicity just add the babel-plugin-after to you babel config do it for you:

https://github.com/jaredpalmer/after.js/blob/master/UPGRADING.md#use-babel-plugin
